apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myhpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 1         # Minimale Anzahl von Replikaten
  maxReplicas: 10        # Maximale Anzahl von Replikaten
  targetCPUUtilizationPercentage: 5  # Ziel-CPU-Auslastung für das Skalieren